routes:
-   distance: ''
    mask: 255.255.255.252
    metric: ''
    network: 10.0.0.12
    nexthopif: outside-1
    nexthopip: ''
    protocol: C
    type: ''
    uptime: ''
-   distance: ''
    mask: 255.255.255.255
    metric: ''
    network: 10.0.0.14
    nexthopif: outside-1
    nexthopip: ''
    protocol: L
    type: ''
    uptime: ''
-   distance: ''
    mask: 255.255.255.252
    metric: ''
    network: 10.0.0.16
    nexthopif: outside-2
    nexthopip: ''
    protocol: C
    type: ''
    uptime: ''
-   distance: ''
    mask: 255.255.255.255
    metric: ''
    network: 10.0.0.17
    nexthopif: outside-2
    nexthopip: ''
    protocol: L
    type: ''
    uptime: ''
