---
- name: Gather LLDP status from NXOS and IOS
  hosts: all
  gather_facts: no

  tasks:
    - name: Get LLDP neighbore at IOS
      block:
        - ios_command:
            commands:
            - show lldp
          register: results
        - set_fact: 
            lldp_enable: false
        - set_fact: 
            lldp_enable: true
          when:  "'not enabled' not in results.stdout_lines[0][0]"
        - debug:
            msg: "hostname {{inventory_hostname}} has LLDP not enabled!"
          when: lldp_enable == false
      when: ansible_network_os == 'ios'

    - name: Enable LLDP at IOS
      block:
      - ios_config:
          lines: 
            - "lldp run"
        when: lldp_enable == false 
      when: ansible_network_os == 'ios'

    - name: Get LLDP neighbore at NXOS
      block:
        - nxos_command:
            commands:
            - show feature | grep lldp
          register: results
        - set_fact: 
            lldp_enable: false          
        - set_fact: 
            lldp_enable: true
          when:  "'disabled' not in results.stdout_lines[0][0]"
        - debug:
            msg: "hostname {{inventory_hostname}} has LLDP not enabled!"
          when: lldp_enable == false
      when: ansible_network_os == 'nxos'

    - name: Enable LLDP at NX-OS
      block:
      - nxos_feature:
          feature: lldp
          state: enabled
        when: lldp_enable == false 
      when: ansible_network_os == 'nxos'
