- name: Gather facts from switches
  hosts: asa
  gather_facts: no

  tasks:
    - name: get current priv level ASA
      asa_command:
        commands:
          - show curpriv
      register: result
      when: ansible_network_os == 'asa'
    
    - debug:
        msg: "hostname {{inventory_hostname}} has privilege level {{result.stdout_lines[0][1].split(': ')[1]}}"
      when: ansible_network_os == 'asa'

    - name: get current priv level (become:yes)
      become: yes
      become_method: enable
      asa_command:
        commands:
          - show curpriv
      register: result
      when: ansible_network_os == 'asa'
    
    - debug:
        msg: "hostname {{inventory_hostname}} has privilege level {{result.stdout_lines[0][1].split(': ')[1]}}"
      when: ansible_network_os == 'asa'
