- name: Gather facts from switches
  hosts: asa
  gather_facts: no

  tasks:
    - name: get current priv level ASA
      block:
      - asa_command:
          commands:
            - show curpriv
        register: result_get
      - debug:
          msg: "hostname {{inventory_hostname}} has privilege level {{result_get.stdout_lines[0][1].split(': ')[1]}}"
      - set_fact: 
          privilege_level: "{{result_get.stdout_lines[0][1].split(': ')[1]}}"
      when: ansible_network_os == 'asa'

    - name: get current priv level (become:yes)
      become: yes
      become_method: enable
      block:
      - asa_command:
          commands:
            - show curpriv
        register: result
      - asa_config:
          lines: 
            - "aaa authorization exec LOCAL auto-enable"
      when: privilege_level == "1" and ansible_network_os == 'asa'