- name: Gather facts from switches
  hosts: all
  gather_facts: no

  tasks:
    ## Collect Data
    - name: Gather facts (ASA)
      become: yes
      become_method: enable
      asa_facts:
      when: ansible_network_os == 'asa'

    - name: Gather facts (IOS / IOS XE)
      ios_facts:
      when: ansible_network_os == 'ios'
    
    - name: Gather facts (NXOS)
      nxos_facts:
      when: ansible_network_os == 'nxos'

    ## Display facts
    - name:
      debug:
        msg: "Hostname: {{ansible_net_hostname}} 
        Managment IP: {{ansible_host}}
        Firmware: {{ansible_net_version}}
        Firmware Image: {{ansible_facts['net_image']}}"

    - name: Display Hostvar for lab-mgmt-asa-01
      debug: 
        var: hostvars['lab-mgmt-asa-01']
      when: inventory_hostname == 'lab-mgmt-asa-01'
