- name: Gather facts from switches
  hosts: all 
  gather_facts: no
  vars:
    - result_directory: saved_state
    - suffix: "_facts"
    - date: "{{ lookup('pipe', 'date +%Y%m%d-%H%M') }}"

  tasks:
    ## Create Directory
    - name: Create directory {{result_directory}}
      file: path={{result_directory}} state=directory
      run_once: true
    ## Collect Data

    - name: Gather facts (ASA)
      block:
      - asa_facts:
        become: yes
        become_method: enable
      - copy:
          content: |
            {{ansible_facts|to_nice_yaml}}
          dest: "{{result_directory}}/{{inventory_hostname}}{{suffix}}.yml"
      when: ansible_network_os == 'asa'

    - name: Gather facts (IOS)
      block:
      - ios_facts:
      - copy:
          content: |
            {{ansible_facts|to_nice_yaml}}
          dest: "{{result_directory}}/{{inventory_hostname}}{{suffix}}.yml"
      when: ansible_network_os == 'ios'

    - name: Gather facts (NXOS)
      block:
      - nxos_facts:
      - copy:
          content: |
            {{ansible_facts|to_nice_yaml}}
          dest: "{{result_directory}}/{{inventory_hostname}}{{suffix}}.yml"
      when: ansible_network_os == 'nxos'