---
- name: Get routing table from all devices
  hosts: all
  gather_facts: no
  tasks:
  - name: "Get Routing Table IOS"
    ios_command:
      commands: show ip route
    register: results
    when: ansible_network_os == 'ios'
  - name: debug results
    debug:
      var: results
    when: ansible_network_os == 'ios'

  - name: "Get Routing Table NXOS"
    asa_command:
      commands: show ip route
    register: results
    when: ansible_network_os == 'nxos'
  - name: debug results
    debug:
      var: results
    when: ansible_network_os == 'nxos'

  - name: "Get Routing Table ASA"
    become: yes
    become_method: enable
    asa_command:
      commands: show route
    register: results
    when: ansible_network_os == 'asa'
  - name: debug results
    debug:
      var: results
    when: ansible_network_os == 'asa'