---
- name: Get routing table from all devices
  hosts: all
  gather_facts: no
  tasks:
    - name: Test reachabilty 192.168.0.12
      net_ping:
        dest: 192.168.0.12
      register: results

    - name: print results
      debug:
        var: results
    
    - name: Test reachabilty 192.168.0.12 ASA
      asa_command:
        commands: ping 192.168.0.12
      register: results
      when: ansible_network_os == 'asa'

    - name: debug results
      debug:
        var: results
      when: ansible_network_os == 'asa'  